[package]
name = "imgtoolkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
image = "0.24.9"
clap = { version = "4.5.1", features = ["cargo"] }
rayon = "1.9.0"
